/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIAssistantPage: typeof import('./src/components/bookkeeping/AIAssistantPage.vue')['default']
    BatchCard: typeof import('./src/components/bookkeeping/BatchCard.vue')['default']
    BatchForm: typeof import('./src/components/bookkeeping/BatchForm.vue')['default']
    BatchFormPage: typeof import('./src/components/bookkeeping/BatchFormPage.vue')['default']
    RecordForm: typeof import('./src/components/bookkeeping/RecordForm.vue')['default']
    RecordFormPage: typeof import('./src/components/bookkeeping/RecordFormPage.vue')['default']
    RecordTimeline: typeof import('./src/components/bookkeeping/RecordTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SummaryCard: typeof import('./src/components/bookkeeping/SummaryCard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
